enum CatSection { varc, dilr, qa }

extension CatSectionInfo on CatSection {
  String get shortName {
    switch (this) {
      case CatSection.varc:
        return 'VARC';
      case CatSection.dilr:
        return 'DILR';
      case CatSection.qa:
        return 'QA';
    }
  }

  String get fullName {
    switch (this) {
      case CatSection.varc:
        return 'Verbal Ability and Reading Comprehension';
      case CatSection.dilr:
        return 'Data Interpretation and Logical Reasoning';
      case CatSection.qa:
        return 'Quantitative Ability';
    }
  }
}

class PrepTopic {
  const PrepTopic({
    required this.id,
    required this.section,
    required this.cluster,
    required this.title,
    required this.detail,
    required this.difficulty,
    required this.weight,
    required this.priority,
    required this.plannedHours,
  });

  final String id;
  final CatSection section;
  final String cluster;
  final String title;
  final String detail;
  final String difficulty;
  final String weight;
  final String priority;
  final int plannedHours;
}

class PrepSubtopic {
  const PrepSubtopic(
    this.id,
    this.title,
    this.about,
    this.weightage,
    this.pastYears,
    this.practiceHint, {
    this.difficulty = 'Core',
  });

  final String id;
  final String title;
  final String about;
  final String weightage;
  final String pastYears;
  final String practiceHint;
  final String difficulty;
}

extension PrepTopicChildren on PrepTopic {
  List<PrepSubtopic> get subtopics => topicSubtopics[id] ?? const [];
}

class DailyTask {
  const DailyTask({
    required this.id,
    required this.section,
    required this.title,
    required this.detail,
    required this.minutes,
  });

  final String id;
  final CatSection? section;
  final String title;
  final String detail;
  final int minutes;
}

class MockSlot {
  MockSlot({
    required this.id,
    required this.title,
    required this.date,
    required this.focus,
    required this.kind,
  });

  final String id;
  final String title;
  final DateTime date;
  final String focus;
  final String kind;
}

class PreviousYearPaper {
  const PreviousYearPaper({
    required this.id,
    required this.year,
    required this.slot,
    required this.questions,
    required this.note,
  });

  final String id;
  final int year;
  final String slot;
  final String questions;
  final String note;

  String get title => 'CAT $year $slot';
}

class PlanPhase {
  PlanPhase({
    required this.title,
    required this.range,
    required this.focus,
    required this.actions,
    required this.start,
    required this.end,
  });

  final String title;
  final String range;
  final String focus;
  final List<String> actions;
  final DateTime start;
  final DateTime end;
}

class ResourceItem {
  const ResourceItem({
    required this.title,
    required this.useFor,
    required this.note,
  });

  final String title;
  final String useFor;
  final String note;
}

final DateTime prepStartDate = DateTime(2026, 6, 13);
final DateTime targetExamDate = DateTime(2026, 11, 29);
const int totalHoursGoal = 300;
const String examDateLabel = '29 Nov 2026';
const String examDateStatus = 'Tentative late-November Sunday target';

String dateKey(DateTime date) {
  final month = date.month.toString().padLeft(2, '0');
  final day = date.day.toString().padLeft(2, '0');
  return '${date.year}-$month-$day';
}

String shortDate(DateTime date) {
  const months = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ];
  return '${date.day} ${months[date.month - 1]}';
}

const List<PrepTopic> catTopics = [
  PrepTopic(
    id: 'varc_rc_main_idea',
    section: CatSection.varc,
    cluster: 'Reading Comprehension',
    title: 'Main idea and central theme',
    detail: 'Identify the passage spine, purpose, and primary claim.',
    difficulty: 'Beginner to Intermediate',
    weight: 'RC is about 16 of 24 questions',
    priority: 'Highest',
    plannedHours: 8,
  ),
  PrepTopic(
    id: 'varc_rc_inference',
    section: CatSection.varc,
    cluster: 'Reading Comprehension',
    title: 'Inference and implication',
    detail: 'Move from stated facts to the answer that must be true.',
    difficulty: 'Intermediate',
    weight: 'High RC frequency',
    priority: 'Highest',
    plannedHours: 8,
  ),
  PrepTopic(
    id: 'varc_rc_tone',
    section: CatSection.varc,
    cluster: 'Reading Comprehension',
    title: 'Tone, stance, and purpose',
    detail: 'Track author attitude, contrast, and intent across paragraphs.',
    difficulty: 'Intermediate',
    weight: 'High RC frequency',
    priority: 'Highest',
    plannedHours: 7,
  ),
  PrepTopic(
    id: 'varc_rc_details',
    section: CatSection.varc,
    cluster: 'Reading Comprehension',
    title: 'Detail, title, and structure questions',
    detail: 'Answer without over-reading or getting trapped by close options.',
    difficulty: 'Intermediate',
    weight: 'High RC frequency',
    priority: 'Highest',
    plannedHours: 7,
  ),
  PrepTopic(
    id: 'varc_rc_passage_themes',
    section: CatSection.varc,
    cluster: 'Reading Comprehension',
    title: 'RC passage themes',
    detail:
        'Practice recurring RC genres: philosophy, psychology, history, arts, society, culture, biology, and science/technology.',
    difficulty: 'Beginner to Intermediate',
    weight: 'Recurring RC topic pool',
    priority: 'High',
    plannedHours: 6,
  ),
  PrepTopic(
    id: 'varc_para_summary',
    section: CatSection.varc,
    cluster: 'Verbal Ability',
    title: 'Para summary',
    detail:
        'Choose the option that preserves the main point without distortion.',
    difficulty: 'Intermediate',
    weight: 'Common VA format',
    priority: 'High',
    plannedHours: 7,
  ),
  PrepTopic(
    id: 'varc_para_completion',
    section: CatSection.varc,
    cluster: 'Verbal Ability',
    title: 'Para completion, insertion, and fill in the blank',
    detail:
        'Place the sentence that completes the logic, blank, or paragraph flow.',
    difficulty: 'Intermediate',
    weight: 'Common VA format',
    priority: 'High',
    plannedHours: 7,
  ),
  PrepTopic(
    id: 'varc_odd_sentence',
    section: CatSection.varc,
    cluster: 'Verbal Ability',
    title: 'Odd sentence out / out of context',
    detail: 'Find the sentence that breaks context, chronology, or scope.',
    difficulty: 'Easy to Moderate',
    weight: 'Rotating VA format',
    priority: 'Medium',
    plannedHours: 5,
  ),
  PrepTopic(
    id: 'varc_para_jumbles',
    section: CatSection.varc,
    cluster: 'Verbal Ability',
    title: 'Para jumbles',
    detail:
        'Build order through opening clues, pronoun links, and transitions.',
    difficulty: 'Intermediate',
    weight: 'Rotating VA format',
    priority: 'Medium',
    plannedHours: 5,
  ),
  PrepTopic(
    id: 'varc_verbal_logic',
    section: CatSection.varc,
    cluster: 'Verbal Ability',
    title: 'Critical reasoning basics',
    detail: 'Practice assumptions, conclusions, and logical deductions.',
    difficulty: 'Intermediate',
    weight: 'Low to Moderate',
    priority: 'Medium',
    plannedHours: 4,
  ),
  PrepTopic(
    id: 'varc_language_clarity',
    section: CatSection.varc,
    cluster: 'Language Clarity',
    title: 'Grammar and vocabulary by context',
    detail: 'Use grammar only to improve reading clarity and elimination.',
    difficulty: 'Beginner',
    weight: 'Rare direct testing',
    priority: 'Low',
    plannedHours: 2,
  ),
  PrepTopic(
    id: 'dilr_tables_graphs',
    section: CatSection.dilr,
    cluster: 'Data Interpretation',
    title: 'Tables, graphs, and chart sets',
    detail:
        'Handle table-based DI, graphs, charts, bar, line, pie, radar, and mixed chart data.',
    difficulty: 'Beginner to Intermediate',
    weight: 'DI-heavy sets rotate yearly',
    priority: 'Highest',
    plannedHours: 12,
  ),
  PrepTopic(
    id: 'dilr_caselets',
    section: CatSection.dilr,
    cluster: 'Data Interpretation',
    title: 'Caselets and multi-source data',
    detail: 'Translate paragraph data into clean tables before solving.',
    difficulty: 'Intermediate',
    weight: 'Frequent',
    priority: 'Highest',
    plannedHours: 12,
  ),
  PrepTopic(
    id: 'dilr_percent_ratio',
    section: CatSection.dilr,
    cluster: 'Data Interpretation',
    title: 'Percent, ratio, average data logic',
    detail: 'Use arithmetic cleanly inside DI without losing time.',
    difficulty: 'Intermediate',
    weight: 'Frequent support skill',
    priority: 'High',
    plannedHours: 8,
  ),
  PrepTopic(
    id: 'dilr_di_quant_networks',
    section: CatSection.dilr,
    cluster: 'Data Interpretation',
    title: 'Quant, network, and mathematical DI',
    detail:
        'Cover quant-based DI, Venn diagrams, networks and diagrams, mathematical puzzles, and maxima-minima data sets.',
    difficulty: 'Intermediate to Advanced',
    weight: 'Rotating DI set family',
    priority: 'Medium',
    plannedHours: 9,
  ),
  PrepTopic(
    id: 'dilr_linear_circular',
    section: CatSection.dilr,
    cluster: 'Logical Reasoning',
    title: 'Linear, circular, and grid arrangements',
    detail: 'Convert constraints into slots, grids, and elimination marks.',
    difficulty: 'Intermediate',
    weight: 'Common LR family',
    priority: 'Highest',
    plannedHours: 12,
  ),
  PrepTopic(
    id: 'dilr_selection_distribution',
    section: CatSection.dilr,
    cluster: 'Logical Reasoning',
    title: 'Selection and distribution',
    detail: 'Track groups, assignments, and either-or conditions.',
    difficulty: 'Intermediate to Advanced',
    weight: 'Common LR family',
    priority: 'Highest',
    plannedHours: 11,
  ),
  PrepTopic(
    id: 'dilr_scheduling_ordering',
    section: CatSection.dilr,
    cluster: 'Logical Reasoning',
    title: 'Scheduling, order, and ranking',
    detail: 'Build timelines, ranks, and conditional order maps.',
    difficulty: 'Intermediate',
    weight: 'Frequent',
    priority: 'High',
    plannedHours: 9,
  ),
  PrepTopic(
    id: 'dilr_games_tournaments',
    section: CatSection.dilr,
    cluster: 'Logical Reasoning',
    title: 'Games and tournaments',
    detail:
        'Read points tables, fixtures, wins, draws, and qualification logic.',
    difficulty: 'Intermediate to Advanced',
    weight: 'Rotating high-value set',
    priority: 'High',
    plannedHours: 9,
  ),
  PrepTopic(
    id: 'dilr_routes_networks',
    section: CatSection.dilr,
    cluster: 'Logical Reasoning',
    title: 'Routes, networks, and paths',
    detail: 'Represent maps, roads, paths, and reachability efficiently.',
    difficulty: 'Intermediate to Advanced',
    weight: 'Rotating high-value set',
    priority: 'Medium',
    plannedHours: 8,
  ),
  PrepTopic(
    id: 'dilr_binary_logic',
    section: CatSection.dilr,
    cluster: 'Logical Reasoning',
    title: 'Binary logic and truth conditions',
    detail: 'Solve true-false, yes-no, and condition chains without guessing.',
    difficulty: 'Intermediate',
    weight: 'Rotating',
    priority: 'Medium',
    plannedHours: 7,
  ),
  PrepTopic(
    id: 'dilr_lr_puzzles',
    section: CatSection.dilr,
    cluster: 'Logical Reasoning',
    title: 'Puzzles and case-based LR',
    detail:
        'Practice puzzle-style LR, conditional LR, coin picking, truth-lie cases, case-based LR, and 2D/3D logic.',
    difficulty: 'Intermediate to Advanced',
    weight: 'Rotating LR set family',
    priority: 'Medium',
    plannedHours: 10,
  ),
  PrepTopic(
    id: 'dilr_hybrid_sets',
    section: CatSection.dilr,
    cluster: 'Hybrid Sets',
    title: 'Hybrid logic-data sets',
    detail: 'Practice mixed sets where table building and logic interact.',
    difficulty: 'Advanced',
    weight: 'Unpredictable but important',
    priority: 'Medium',
    plannedHours: 12,
  ),
  PrepTopic(
    id: 'qa_percentages',
    section: CatSection.qa,
    cluster: 'Arithmetic',
    title: 'Percentages and change',
    detail: 'Build speed with percentage change, comparison, and base shifts.',
    difficulty: 'Beginner',
    weight: 'Arithmetic is about 33-45% of QA',
    priority: 'Highest',
    plannedHours: 8,
  ),
  PrepTopic(
    id: 'qa_averages',
    section: CatSection.qa,
    cluster: 'Arithmetic',
    title: 'Averages and mixtures',
    detail: 'Master weighted averages, alligation, and replacement logic.',
    difficulty: 'Beginner to Intermediate',
    weight: 'High Arithmetic frequency',
    priority: 'Highest',
    plannedHours: 8,
  ),
  PrepTopic(
    id: 'qa_ratio',
    section: CatSection.qa,
    cluster: 'Arithmetic',
    title: 'Ratio, proportion, and variation',
    detail: 'Set up equations from ratio language and proportional change.',
    difficulty: 'Beginner to Intermediate',
    weight: 'High Arithmetic frequency',
    priority: 'Highest',
    plannedHours: 8,
  ),
  PrepTopic(
    id: 'qa_profit_loss',
    section: CatSection.qa,
    cluster: 'Arithmetic',
    title: 'Profit, loss, discount, SI, and CI',
    detail: 'Handle business arithmetic and compounding without formula panic.',
    difficulty: 'Beginner to Intermediate',
    weight: 'High Arithmetic frequency',
    priority: 'Highest',
    plannedHours: 8,
  ),
  PrepTopic(
    id: 'qa_tsd',
    section: CatSection.qa,
    cluster: 'Arithmetic',
    title: 'Time, speed, distance, and races',
    detail: 'Convert movement stories into rate equations and relative speed.',
    difficulty: 'Intermediate',
    weight: 'High Arithmetic frequency',
    priority: 'Highest',
    plannedHours: 8,
  ),
  PrepTopic(
    id: 'qa_time_work',
    section: CatSection.qa,
    cluster: 'Arithmetic',
    title: 'Time and work',
    detail: 'Use efficiency, LCM, and work-rate thinking under time limits.',
    difficulty: 'Intermediate',
    weight: 'High Arithmetic frequency',
    priority: 'High',
    plannedHours: 6,
  ),
  PrepTopic(
    id: 'qa_linear_quadratic',
    section: CatSection.qa,
    cluster: 'Algebra',
    title: 'Linear and quadratic equations',
    detail: 'Translate word problems, roots, and equation systems.',
    difficulty: 'Intermediate',
    weight: 'Algebra is about 23-36% of QA',
    priority: 'Highest',
    plannedHours: 9,
  ),
  PrepTopic(
    id: 'qa_inequalities',
    section: CatSection.qa,
    cluster: 'Algebra',
    title: 'Inequalities and modulus',
    detail: 'Solve ranges, cases, and sign charts without overcomplication.',
    difficulty: 'Intermediate to Advanced',
    weight: 'Common Algebra family',
    priority: 'High',
    plannedHours: 7,
  ),
  PrepTopic(
    id: 'qa_functions_logs',
    section: CatSection.qa,
    cluster: 'Algebra',
    title: 'Functions and logarithms',
    detail: 'Practice composition, domains, graphs, and log rules.',
    difficulty: 'Intermediate',
    weight: 'Common Algebra family',
    priority: 'High',
    plannedHours: 7,
  ),
  PrepTopic(
    id: 'qa_algebra_polynomials',
    section: CatSection.qa,
    cluster: 'Algebra',
    title: 'Polynomials, surds, and indices',
    detail:
        'Cover polynomial expressions, algebraic identities, roots, indices, and surd simplification.',
    difficulty: 'Intermediate',
    weight: 'Common Algebra support family',
    priority: 'Medium',
    plannedHours: 5,
  ),
  PrepTopic(
    id: 'qa_sequences',
    section: CatSection.qa,
    cluster: 'Modern Math',
    title: 'Series and progressions',
    detail:
        'Cover AP, GP, HP, sums, and pattern recognition for Modern Math and Algebra crossover.',
    difficulty: 'Intermediate',
    weight: 'Common Algebra family',
    priority: 'High',
    plannedHours: 6,
  ),
  PrepTopic(
    id: 'qa_geometry_triangles',
    section: CatSection.qa,
    cluster: 'Geometry',
    title: 'Lines, triangles, circles, and polygons',
    detail:
        'Build lines and angles, triangles, circles, polygons, quadrilaterals, and diagram discipline.',
    difficulty: 'Intermediate',
    weight: 'Geometry is about 10-18% of QA',
    priority: 'Medium',
    plannedHours: 8,
  ),
  PrepTopic(
    id: 'qa_coordinate_mensuration',
    section: CatSection.qa,
    cluster: 'Geometry',
    title: 'Coordinate geometry and mensuration',
    detail: 'Cover slopes, distance, areas, volumes, and standard shapes.',
    difficulty: 'Intermediate',
    weight: 'Moderate',
    priority: 'Medium',
    plannedHours: 7,
  ),
  PrepTopic(
    id: 'qa_number_system',
    section: CatSection.qa,
    cluster: 'Number System',
    title: 'Divisibility, remainders, and factors',
    detail: 'Practice HCF, LCM, factor counts, and modular patterns.',
    difficulty: 'Intermediate',
    weight: 'About 5-15% of QA',
    priority: 'Medium',
    plannedHours: 7,
  ),
  PrepTopic(
    id: 'qa_digits_bases',
    section: CatSection.qa,
    cluster: 'Number System',
    title: 'Digits, base systems, exponents, and surds',
    detail: 'Cover units digits, bases, indices, and simplification tricks.',
    difficulty: 'Intermediate',
    weight: 'Low to Moderate',
    priority: 'Medium',
    plannedHours: 5,
  ),
  PrepTopic(
    id: 'qa_sets_pnc_probability',
    section: CatSection.qa,
    cluster: 'Modern Math',
    title: 'Set theory, P&C, and probability',
    detail: 'Build enough coverage for rotating modern math questions.',
    difficulty: 'Intermediate to Advanced',
    weight: 'About 0-14% of QA',
    priority: 'Medium',
    plannedHours: 7,
  ),
  PrepTopic(
    id: 'qa_maxima_integer',
    section: CatSection.qa,
    cluster: 'Algebra',
    title: 'Maxima-minima and integer solutions',
    detail: 'Handle optimization, constraints, and countable equation cases.',
    difficulty: 'Advanced',
    weight: 'Rotating',
    priority: 'Low',
    plannedHours: 6,
  ),
];

final Map<String, List<PrepSubtopic>> topicSubtopics = {
  'varc_rc_main_idea': [
    const PrepSubtopic(
      'varc_rc_main_idea_core',
      'Central idea',
      'Find the one sentence that captures the passage spine.',
      'RC carries about 60-70% of VARC.',
      '2021-25 trend: usually 16 RC questions out of 24.',
      'Write a 12-word summary after every passage.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'varc_rc_main_idea_scope',
      'Scope control',
      'Separate the main argument from examples and side details.',
      'High frequency inside RC sets.',
      'Appears every year through main idea and title questions.',
      'Reject options that are too broad, too narrow, or too extreme.',
    ),
    const PrepSubtopic(
      'varc_rc_main_idea_titles',
      'Title questions',
      'Choose a title that matches both subject and argument.',
      'Common RC question type.',
      'Seen regularly across recent RC sets.',
      'Check whether the title covers all paragraphs, not just one.',
    ),
    const PrepSubtopic(
      'varc_rc_main_idea_paragraph_role',
      'Paragraph role',
      'Track what each paragraph does in the argument.',
      'Support skill for RC accuracy.',
      'Recurring in structure and purpose questions.',
      'Label each paragraph as claim, contrast, evidence, or conclusion.',
    ),
  ],
  'varc_rc_inference': [
    const PrepSubtopic(
      'varc_rc_inference_must_be_true',
      'Must-be-true inference',
      'Select the option that follows from the passage without adding assumptions.',
      'Very high RC value.',
      'Inference questions appear in almost every recent CAT RC set.',
      'Ask: can I prove this from the text?',
    ),
    const PrepSubtopic(
      'varc_rc_inference_application',
      'Application inference',
      'Apply the author logic to a fresh situation or example.',
      'Common in difficult RC passages.',
      'Frequent in 2020-25 RC analyses.',
      'Map the new example to the original principle.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'varc_rc_inference_negative',
      'Except and not questions',
      'Handle negative wording without losing track of the ask.',
      'Moderate frequency.',
      'Rotates yearly but is common enough to train.',
      'Mark three true options first, then select the exception.',
    ),
    const PrepSubtopic(
      'varc_rc_inference_option_traps',
      'Close-option elimination',
      'Spot half-true, extreme, opposite, and out-of-scope options.',
      'High score separator.',
      'Consistently relevant across RC-heavy VARC papers.',
      'Keep an error note for every trap pattern.',
    ),
  ],
  'varc_rc_tone': [
    const PrepSubtopic(
      'varc_rc_tone_author_stance',
      'Author stance',
      'Identify whether the author supports, criticises, qualifies, or compares.',
      'Common RC skill.',
      'Appears through tone, attitude, and purpose questions.',
      'Underline contrast words and value-loaded adjectives.',
    ),
    const PrepSubtopic(
      'varc_rc_tone_words',
      'Tone vocabulary',
      'Distinguish cautious, sceptical, critical, neutral, and optimistic tones.',
      'Low direct weight, high usefulness.',
      'Tone labels recur, even when direct vocabulary does not.',
      'Build a small tone-word deck from solved passages.',
    ),
    const PrepSubtopic(
      'varc_rc_tone_purpose',
      'Author purpose',
      'Find whether the passage explains, argues, challenges, or reconciles.',
      'Common RC type.',
      'Regularly tested in main idea and structure questions.',
      'Use the final paragraph to confirm purpose.',
    ),
    const PrepSubtopic(
      'varc_rc_tone_shifts',
      'Tone shifts',
      'Notice when the author moves from description to judgement.',
      'Useful in tougher RCs.',
      'Seen in philosophy, social science, and policy passages.',
      'Mark "however", "yet", "but", and "therefore".',
      difficulty: 'Advanced',
    ),
  ],
  'varc_rc_details': [
    const PrepSubtopic(
      'varc_rc_details_direct',
      'Direct detail',
      'Return to the exact line and avoid memory-based answering.',
      'Common RC support type.',
      'Direct detail questions appear regularly across RC sets.',
      'Locate proof before reading all options deeply.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'varc_rc_details_structure',
      'Structure map',
      'Understand how examples, contrasts, and conclusions connect.',
      'High-value RC skill.',
      'Recurring in structure and paragraph role questions.',
      'Create a 4-line passage map after practice RCs.',
    ),
    const PrepSubtopic(
      'varc_rc_details_data_examples',
      'Examples and evidence',
      'Know why an example exists instead of only what it says.',
      'Moderate frequency.',
      'Common in science, culture, economics, and policy RCs.',
      'Ask: what claim does this example support?',
    ),
    const PrepSubtopic(
      'varc_rc_details_time_selection',
      'Passage selection',
      'Choose the RC passage you can read cleanly under time pressure.',
      'Score multiplier in RC-heavy VARC.',
      'Relevant every year because RC is the section core.',
      'Track passage genre, time taken, and accuracy.',
      difficulty: 'Advanced',
    ),
  ],
  'varc_rc_passage_themes': [
    const PrepSubtopic(
      'varc_rc_themes_philosophy',
      'Philosophy',
      'Read dense abstract arguments, definitions, and counter-positions.',
      'Recurring RC genre.',
      'Philosophy-style passages appear often in past-paper analyses.',
      'Slow down on scope words and author stance.',
    ),
    const PrepSubtopic(
      'varc_rc_themes_psychology',
      'Psychology',
      'Handle behaviour, cognition, decision-making, and experiment-based passages.',
      'Recurring RC genre.',
      'Psychology and social-science passages are common RC practice areas.',
      'Separate study findings from author interpretation.',
    ),
    const PrepSubtopic(
      'varc_rc_themes_history',
      'History',
      'Track chronology, causation, and interpretation of historical events.',
      'Recurring RC genre.',
      'History passages rotate through CAT-style RC sets.',
      'Mark timeline shifts and the author judgement.',
    ),
    const PrepSubtopic(
      'varc_rc_themes_arts_museum',
      'Arts and museum',
      'Read passages on art, aesthetics, museums, literature, and criticism.',
      'Recurring RC genre.',
      'Arts and culture topics recur in RC passage pools.',
      'Ask what the example proves, not whether you like the topic.',
    ),
    const PrepSubtopic(
      'varc_rc_themes_society',
      'Society',
      'Handle social structures, policy, economics, and institutional arguments.',
      'Recurring RC genre.',
      'Society and policy passages are frequent in RC-heavy papers.',
      'Track cause-effect claims and qualifying words.',
    ),
    const PrepSubtopic(
      'varc_rc_themes_culture',
      'Culture',
      'Read cultural practices, identity, language, and anthropology themes.',
      'Recurring RC genre.',
      'Culture passages appear regularly in broad RC topic lists.',
      'Avoid bringing outside assumptions into option elimination.',
    ),
    const PrepSubtopic(
      'varc_rc_themes_biology',
      'Biology',
      'Understand life-science explanations without getting stuck on jargon.',
      'Recurring RC genre.',
      'Science RCs often include biology or ecology themes.',
      'Translate technical terms into simple relationships.',
    ),
    const PrepSubtopic(
      'varc_rc_themes_science_technology',
      'Science and technology',
      'Read scientific method, technology, AI, environment, and discovery passages.',
      'Recurring RC genre.',
      'Science and technology passages recur in CAT RC practice.',
      'Map claim, evidence, and limitation before answering.',
    ),
  ],
  'varc_para_summary': [
    const PrepSubtopic(
      'varc_para_summary_main_point',
      'Main-point capture',
      'Keep the core claim and remove examples or side facts.',
      'VA is about 8 questions; summary is common.',
      '2022-25 trend: usually 2-3 summary questions.',
      'Write your own summary before seeing options.',
    ),
    const PrepSubtopic(
      'varc_para_summary_distortion',
      'Distortion traps',
      'Reject options that change cause, scope, or author stance.',
      'High-value VA skill.',
      'Common every year summary appears.',
      'Circle the word that makes a wrong option wrong.',
    ),
    const PrepSubtopic(
      'varc_para_summary_missing_piece',
      'Missing-piece traps',
      'Reject options that ignore an important contrast or conclusion.',
      'Common summary trap.',
      'Frequent across current-format VARC papers.',
      'Check every sentence in the paragraph is represented fairly.',
    ),
    const PrepSubtopic(
      'varc_para_summary_concision',
      'Concise wording',
      'Prefer precise summaries over wordy but incomplete options.',
      'Moderate frequency.',
      'Useful whenever summary questions appear.',
      'Do not reward fancy wording unless logic is complete.',
    ),
  ],
  'varc_para_completion': [
    const PrepSubtopic(
      'varc_para_completion_fill_blank',
      'Fill in the blank',
      'Choose the missing sentence or phrase that keeps the paragraph logic intact.',
      'Common VA format.',
      'Appears through para completion and best-fit sentence variants.',
      'Predict the missing role before reading options.',
    ),
    const PrepSubtopic(
      'varc_para_completion_flow',
      'Logical flow',
      'Choose the sentence that follows the previous idea naturally.',
      'Common VA format.',
      '2023-25 trend: para completion/insertion appeared regularly.',
      'Predict the missing idea before checking options.',
    ),
    const PrepSubtopic(
      'varc_para_completion_connectors',
      'Connectors and references',
      'Use pronouns, this/that references, and transition words.',
      'High accuracy lever.',
      'Recurring in para insertion and completion questions.',
      'Match pronouns to exact nouns.',
    ),
    const PrepSubtopic(
      'varc_para_completion_open_close',
      'Opening and closing logic',
      'Spot whether the missing sentence introduces or concludes the paragraph.',
      'Moderate VA weight.',
      'Appears in best-fit sentence formats.',
      'Check if the option needs prior context.',
    ),
    const PrepSubtopic(
      'varc_para_completion_contrast',
      'Contrast handling',
      'Track when the missing line must oppose the previous claim.',
      'Common in harder VA.',
      'Rotates yearly with insertion/completion mix.',
      'Watch for but, however, while, although.',
      difficulty: 'Advanced',
    ),
  ],
  'varc_odd_sentence': [
    const PrepSubtopic(
      'varc_odd_sentence_theme',
      'Theme mismatch',
      'Find the sentence that belongs to a different discussion.',
      'Rotating VA format.',
      '2023-25 trend: often 2 odd-sentence questions when present.',
      'Build the paragraph from the four connected sentences.',
    ),
    const PrepSubtopic(
      'varc_odd_sentence_chronology',
      'Chronology mismatch',
      'Use time order to expose the out-of-place sentence.',
      'Moderate VA value.',
      'Appears in odd sentence and para jumble logic.',
      'Look for before, after, first, later, finally.',
    ),
    const PrepSubtopic(
      'varc_odd_sentence_reference',
      'Reference mismatch',
      'Catch pronouns and examples that do not attach to the paragraph.',
      'Useful in VA TITA.',
      'Recurring whenever odd sentence appears.',
      'Every pronoun must have a clean parent.',
    ),
    const PrepSubtopic(
      'varc_odd_sentence_scope',
      'Scope shift',
      'Identify a sentence that is related but not part of the same argument.',
      'Common trap type.',
      'Seen in recent VA practice and paper analysis.',
      'Related is not enough; it must be necessary.',
    ),
  ],
  'varc_para_jumbles': [
    const PrepSubtopic(
      'varc_para_jumbles_openers',
      'Opening sentence',
      'Find the broad independent statement that can start the paragraph.',
      'Rotating VA format.',
      '2022-23 and 2025 had para jumble presence; 2024 varied.',
      'Reject sentences starting with unexplained pronouns.',
    ),
    const PrepSubtopic(
      'varc_para_jumbles_pairs',
      'Mandatory pairs',
      'Lock sentence pairs using pronouns, examples, and cause-effect.',
      'High-value PJ skill.',
      'Useful every year para jumbles appear.',
      'Build pairs before building the full order.',
    ),
    const PrepSubtopic(
      'varc_para_jumbles_sequence',
      'Sequence logic',
      'Arrange definition, example, contrast, and conclusion.',
      'Moderate VA weight.',
      'Rotating yearly in the VA mix.',
      'Use a rough skeleton: intro, development, shift, close.',
    ),
    const PrepSubtopic(
      'varc_para_jumbles_tita',
      'TITA discipline',
      'Avoid random answers and use confident pair-based ordering.',
      'No negative marking, but time is the cost.',
      'Para jumbles are often TITA when present.',
      'Attempt only when at least two links are strong.',
      difficulty: 'Advanced',
    ),
  ],
  'varc_verbal_logic': [
    const PrepSubtopic(
      'varc_verbal_logic_assumptions',
      'Assumptions',
      'Find the unstated belief needed by an argument.',
      'Low direct weight, high reasoning value.',
      'Sometimes appears through critical reasoning style VA.',
      'Use the negation test.',
    ),
    const PrepSubtopic(
      'varc_verbal_logic_conclusions',
      'Conclusions',
      'Separate conclusion, evidence, and background.',
      'Support skill for RC and VA.',
      'Relevant across all argument-heavy passages.',
      'Ask: what is the author trying to prove?',
    ),
    const PrepSubtopic(
      'varc_verbal_logic_strengthen_weaken',
      'Strengthen and weaken',
      'Know what makes an argument more or less believable.',
      'Low to moderate direct frequency.',
      'Useful when RC asks author stance or implication.',
      'Attack the link between evidence and conclusion.',
    ),
    const PrepSubtopic(
      'varc_verbal_logic_syllogisms',
      'Syllogistic reasoning',
      'Handle all/some/no statements only as reasoning support.',
      'Rare direct CAT VARC testing.',
      'Mentioned in prep lists, but less central than RC.',
      'Keep it light; do not over-invest early.',
      difficulty: 'Low Priority',
    ),
  ],
  'varc_language_clarity': [
    const PrepSubtopic(
      'varc_language_sva',
      'Subject-verb agreement',
      'Use grammar to read long sentences cleanly.',
      'Rare direct testing.',
      'Direct grammar is mostly absent in recent CAT VARC.',
      'Study only as a comprehension tool.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'varc_language_modifiers',
      'Modifiers',
      'Understand what phrase describes what noun or action.',
      'Indirect RC usefulness.',
      'Helps with dense RC sentences every year.',
      'Break long sentences into subject, verb, object.',
    ),
    const PrepSubtopic(
      'varc_language_vocab_context',
      'Vocabulary by context',
      'Infer word meaning from surrounding logic.',
      'Rare direct testing.',
      'Vocabulary cramming has low direct ROI in recent CAT.',
      'Note words only from actual RC practice.',
    ),
    const PrepSubtopic(
      'varc_language_idioms',
      'Idioms and foreign words',
      'Keep a light list for reading comfort, not heavy memorisation.',
      'Very low direct frequency.',
      'Appears in broad syllabi but rarely as direct CAT questions.',
      'Spend time here only after RC habit is stable.',
      difficulty: 'Low Priority',
    ),
  ],
  'dilr_tables_graphs': [
    const PrepSubtopic(
      'dilr_tables_graphs_tables',
      'Tables',
      'Read rows, columns, missing values, and totals accurately.',
      'DILR has 20-22 questions across 4-5 sets.',
      '2024-25 trend: five-set DILR with DI-heavy sets rotating.',
      'Rewrite the table before calculating if the data is dense.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'dilr_tables_graphs_bar_line',
      'Bar and line graphs',
      'Compare values, trends, growth, and crossings.',
      'Common DI family.',
      'Appears repeatedly across recent DI set types.',
      'Convert visual values into a small calculation table.',
    ),
    const PrepSubtopic(
      'dilr_tables_graphs_pie_radar',
      'Pie, radar, and point graphs',
      'Handle proportions and less familiar visual formats.',
      'Rotating DI family.',
      '2024-25 analyses mention radar/point/candlestick style sets.',
      'First decode the graph format, then solve.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'dilr_tables_graphs_mixed',
      'Mixed charts',
      'Combine two or more chart sources into one clean setup.',
      'High-value DI skill.',
      'Frequent because CAT likes hybrid data sets.',
      'Identify the common variable across charts.',
    ),
  ],
  'dilr_caselets': [
    const PrepSubtopic(
      'dilr_caselets_text_to_table',
      'Text to table',
      'Translate a paragraph caselet into a grid before solving.',
      'Core DILR skill.',
      'Caselets recur across the 2020-25 window.',
      'Do not calculate until the structure is visible.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'dilr_caselets_missing_data',
      'Missing data',
      'Use constraints to fill unknowns and test possible values.',
      'Moderate to high DI value.',
      'Missing-data sets appear as rotating DI formats.',
      'Mark fixed values and possible ranges separately.',
    ),
    const PrepSubtopic(
      'dilr_caselets_multi_source',
      'Multi-source caselets',
      'Combine text, tables, and conditions without duplicating work.',
      'High-value current CAT skill.',
      'Seen in hybrid DI-LR patterns in recent years.',
      'Create one master table, not many mini tables.',
    ),
    const PrepSubtopic(
      'dilr_caselets_data_sufficiency',
      'Data sufficiency thinking',
      'Know when the information is enough to answer a question.',
      'Moderate support skill.',
      'Useful in caselet and hybrid sets.',
      'Avoid solving more than the question asks.',
    ),
  ],
  'dilr_percent_ratio': [
    const PrepSubtopic(
      'dilr_percent_ratio_percent',
      'Percent change',
      'Calculate percentage rise, fall, contribution, and share.',
      'Frequent support math in DI.',
      'Relevant to almost every DI-heavy paper.',
      'Use base values carefully.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'dilr_percent_ratio_ratio',
      'Ratios',
      'Convert data relationships into parts and totals.',
      'Common DI support skill.',
      'Repeated through tables, caselets, and graph sets.',
      'Keep ratios in simplest form until final calculation.',
    ),
    const PrepSubtopic(
      'dilr_percent_ratio_average',
      'Averages',
      'Handle weighted averages, missing totals, and comparisons.',
      'Frequent in DI and QA.',
      'Mean/median/mode logic appears in hybrid sets too.',
      'Use total = average x count.',
    ),
    const PrepSubtopic(
      'dilr_percent_ratio_growth',
      'Growth rates',
      'Work with CAGR-like and year-on-year growth patterns.',
      'Rotating DI skill.',
      'Seen in business and import-export style sets.',
      'Write old, change, and new values in columns.',
    ),
  ],
  'dilr_di_quant_networks': [
    const PrepSubtopic(
      'dilr_di_quant_networks_quant_based',
      'Quant-based DI',
      'Use arithmetic, averages, ratios, and constraints inside a DI set.',
      'Rotating DI support family.',
      'Quant-heavy DI sets appear often in mock and past-paper analysis.',
      'Write formulas beside the table before calculating.',
    ),
    const PrepSubtopic(
      'dilr_di_quant_networks_networks_diagrams',
      'Networks and diagrams',
      'Interpret nodes, links, flows, diagrams, and connected data structures.',
      'Rotating DI family.',
      'Network and diagram sets recur in DILR topic lists.',
      'Redraw the diagram cleanly and label forced links.',
    ),
    const PrepSubtopic(
      'dilr_di_quant_networks_venn',
      'Venn diagram data sets',
      'Use inclusion-exclusion and overlapping categories in DI-style sets.',
      'Rotating DI/LR family.',
      'Venn sets are part of broad DILR coverage.',
      'Fill the innermost overlap first, then work outward.',
    ),
    const PrepSubtopic(
      'dilr_di_quant_networks_math_puzzle',
      'Mathematical puzzle',
      'Solve number-logic and calculation puzzles presented as data sets.',
      'Rotating high-difficulty family.',
      'Mathematical puzzle sets are useful for unpredictable DILR slots.',
      'Find the governing rule before doing bulk calculation.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'dilr_di_quant_networks_maxima_minima',
      'Maxima-minima DI',
      'Find best and worst possible values under data constraints.',
      'Rotating advanced DI family.',
      'Max-min reasoning appears in set-selection and DI puzzle lists.',
      'Use bounds first, exact values second.',
      difficulty: 'Advanced',
    ),
  ],
  'dilr_linear_circular': [
    const PrepSubtopic(
      'dilr_linear_circular_linear',
      'Linear arrangement',
      'Place people or objects in a row using relative constraints.',
      'Common LR family.',
      'Arrangement sets recur often in 2020-25 analyses.',
      'Draw slots before reading all questions.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'dilr_linear_circular_circular',
      'Circular arrangement',
      'Handle clockwise/anticlockwise positions and fixed references.',
      'Rotating LR family.',
      '2025 analyses mention circular arrangements.',
      'Fix one position to remove rotation ambiguity.',
    ),
    const PrepSubtopic(
      'dilr_linear_circular_grid',
      'Grid and matrix arrangement',
      'Use row-column grids for multi-attribute placement.',
      'High-value LR structure.',
      'Common in assignment and matrix style sets.',
      'Keep confirmed, impossible, and possible marks distinct.',
    ),
    const PrepSubtopic(
      'dilr_linear_circular_conditions',
      'Conditional placement',
      'Split cases only when a condition forces two clean branches.',
      'Advanced set-selection skill.',
      'Important in difficult arrangement sets.',
      'Do not create more than two branches early.',
      difficulty: 'Advanced',
    ),
  ],
  'dilr_selection_distribution': [
    const PrepSubtopic(
      'dilr_selection_distribution_grouping',
      'Grouping',
      'Select members into teams or categories under constraints.',
      'Common LR family.',
      'Selection/distribution appears regularly in DILR rotations.',
      'Track selected, rejected, and undecided items separately.',
    ),
    const PrepSubtopic(
      'dilr_selection_distribution_assignment',
      'Assignment',
      'Assign people, tasks, cities, or slots with multiple attributes.',
      'High-value LR family.',
      '2024 star-assignment style sets show this family.',
      'Use a matrix with attributes as columns.',
    ),
    const PrepSubtopic(
      'dilr_selection_distribution_either_or',
      'Either-or constraints',
      'Handle exclusive choices and dependency chains.',
      'Common difficulty booster.',
      'Appears in many current-format LR sets.',
      'Mark implications with arrows.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'dilr_selection_distribution_counting',
      'Counting valid cases',
      'Count possible arrangements without listing everything.',
      'Moderate to advanced.',
      'Used when DILR asks number of possibilities.',
      'List cases only after simplifying constraints.',
    ),
  ],
  'dilr_scheduling_ordering': [
    const PrepSubtopic(
      'dilr_scheduling_ordering_days',
      'Days and time slots',
      'Place events across days, sessions, or time windows.',
      'Common LR family.',
      'Training/schedule sets appear in recent analyses.',
      'Draw the timeline first.',
    ),
    const PrepSubtopic(
      'dilr_scheduling_ordering_ranking',
      'Ranking',
      'Track greater-than, less-than, before, after, and rank gaps.',
      'Moderate frequency.',
      'Order/ranking stays in the recurring DILR syllabus.',
      'Convert sentences into inequalities.',
    ),
    const PrepSubtopic(
      'dilr_scheduling_ordering_sequences',
      'Sequence constraints',
      'Build valid sequences under adjacency and non-adjacency rules.',
      'High-value LR support skill.',
      'Appears in ordering and scheduling variants.',
      'Place fixed anchors first.',
    ),
    const PrepSubtopic(
      'dilr_scheduling_ordering_cases',
      'Case pruning',
      'Drop impossible schedules early without over-solving.',
      'Important timed-solver skill.',
      'Relevant every year due to set-selection pressure.',
      'If a case is not shrinking in two minutes, leave it.',
      difficulty: 'Advanced',
    ),
  ],
  'dilr_games_tournaments': [
    const PrepSubtopic(
      'dilr_games_tournaments_points',
      'Points tables',
      'Decode wins, draws, losses, points, and qualification.',
      'Rotating high-value LR set.',
      'Tournament/game sets are common in recent DILR trend lists.',
      'Write each team row with fixed score equations.',
    ),
    const PrepSubtopic(
      'dilr_games_tournaments_fixtures',
      'Fixtures',
      'Track who plays whom and how many games remain.',
      'Moderate to advanced.',
      'Appears in games and tournament families.',
      'Build the match matrix.',
    ),
    const PrepSubtopic(
      'dilr_games_tournaments_scenarios',
      'Possible scenarios',
      'Use max/min outcomes to test qualification or ranking.',
      'Advanced but high-return.',
      'Common in tougher tournament sets.',
      'Use bounds before exact enumeration.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'dilr_games_tournaments_scoring',
      'Scoring rules',
      'Handle custom scoring systems without assuming sports defaults.',
      'Rotating CAT style.',
      'CAT often invents set-specific rules.',
      'Rewrite the scoring rule in your own symbols.',
    ),
  ],
  'dilr_routes_networks': [
    const PrepSubtopic(
      'dilr_routes_networks_paths',
      'Path counting',
      'Count possible routes between nodes under restrictions.',
      'Rotating DILR family.',
      'Routes and networks appear in recent trend lists.',
      'Draw nodes cleanly before solving.',
    ),
    const PrepSubtopic(
      'dilr_routes_networks_shortest',
      'Shortest and longest path',
      'Find distance or time using route constraints.',
      'Moderate frequency.',
      'Network-road style sets appear in recent analyses.',
      'Avoid mental maps; redraw the network.',
    ),
    const PrepSubtopic(
      'dilr_routes_networks_connectivity',
      'Connectivity',
      'Check reachability, disconnected nodes, and mandatory links.',
      'Useful in route/network sets.',
      'Rotates with graph-like DILR.',
      'Mark forced edges first.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'dilr_routes_networks_schedule',
      'Route plus schedule',
      'Combine movement with time windows or order conditions.',
      'Advanced hybrid family.',
      'Relevant to travel-currency and route mixed sets.',
      'Create route table and time table separately.',
      difficulty: 'Advanced',
    ),
  ],
  'dilr_binary_logic': [
    const PrepSubtopic(
      'dilr_binary_logic_true_false',
      'True-false statements',
      'Track truth values and contradictions.',
      'Rotating LR family.',
      'Binary/tapping logic appeared in recent analyses.',
      'Use T/F columns, not paragraphs.',
    ),
    const PrepSubtopic(
      'dilr_binary_logic_yes_no',
      'Yes-no grids',
      'Represent binary choices across multiple people or items.',
      'Moderate frequency.',
      'Useful in selection and truth-condition sets.',
      'Fill impossibilities before confirmations.',
    ),
    const PrepSubtopic(
      'dilr_binary_logic_implications',
      'Implication chains',
      'Use if-then statements and contrapositives carefully.',
      'Advanced support skill.',
      'Common in tougher logical conditions.',
      'Write A -> B and not B -> not A.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'dilr_binary_logic_cases',
      'Binary case split',
      'Split on one high-impact yes/no variable.',
      'Set-selection skill.',
      'Useful when binary sets look open-ended.',
      'Pick the variable connected to most conditions.',
    ),
  ],
  'dilr_lr_puzzles': [
    const PrepSubtopic(
      'dilr_lr_puzzles_general',
      'Puzzles',
      'Solve standalone logic puzzles by converting clues into cases or grids.',
      'Core LR umbrella area.',
      'Puzzle-style LR appears across DILR topic lists.',
      'Identify the representation before attempting questions.',
    ),
    const PrepSubtopic(
      'dilr_lr_puzzles_conditional',
      'Conditional LRs',
      'Work with if-then constraints, dependencies, and valid case branches.',
      'Common difficulty booster.',
      'Conditional reasoning is frequent inside LR sets.',
      'Write implications and their consequences clearly.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'dilr_lr_puzzles_coin_picking',
      'Coin picking',
      'Handle selection puzzles involving choices, weights, or picking rules.',
      'Rotating puzzle family.',
      'Coin-picking style sets appear in broad LR syllabi.',
      'Track picked, unpicked, and uncertain states separately.',
    ),
    const PrepSubtopic(
      'dilr_lr_puzzles_truth_lie',
      'Truth and lie',
      'Solve liar-truth teller statements using contradictions and cases.',
      'Rotating LR family.',
      'Truth-lie logic is a known LR puzzle type.',
      'Assume one statement pattern, test quickly, then reject contradictions.',
    ),
    const PrepSubtopic(
      'dilr_lr_puzzles_case_based',
      'Case-based LRs',
      'Break open-ended logic sets into a few useful cases.',
      'High-value DILR skill.',
      'Case-based LR is common in tough practice sets.',
      'Branch only on constraints connected to multiple clues.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'dilr_lr_puzzles_2d_3d',
      '2D and 3D LR',
      'Visualise two-dimensional and three-dimensional arrangements or objects.',
      'Rotating LR puzzle family.',
      '2D/3D LR appears in broad DILR topic lists.',
      'Sketch layers or views instead of holding the image mentally.',
      difficulty: 'Advanced',
    ),
  ],
  'dilr_hybrid_sets': [
    const PrepSubtopic(
      'dilr_hybrid_sets_di_lr',
      'DI plus LR hybrid',
      'Combine numerical tables with arrangement or selection logic.',
      'Very important because CAT mixes set types.',
      '2024-25 trend: five diverse sets with hybrid behaviour.',
      'Identify whether data or logic unlocks the set first.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'dilr_hybrid_sets_math_logic',
      'Math logic sets',
      'Use averages, ratios, or number conditions inside logic grids.',
      'Rotating high-difficulty set.',
      'Mean/median/mode and mixed logic appear in trend lists.',
      'Write formulas beside the grid.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'dilr_hybrid_sets_selection',
      'Set selection',
      'Decide within 2 minutes whether a set is worth solving.',
      'Critical DILR score skill.',
      'Relevant every year because only 2-3 sets may be ideal.',
      'Rate each set as green, amber, or red before deep solving.',
    ),
    const PrepSubtopic(
      'dilr_hybrid_sets_review',
      'Post-set review',
      'Record why a set was slow: representation, calculation, or selection.',
      'Improves mock performance.',
      'Mock analysis is repeatedly recommended in your PDFs.',
      'Do not take two mocks without reviewing the first.',
    ),
  ],
  'qa_percentages': [
    const PrepSubtopic(
      'qa_percentages_basic',
      'Basic percentage conversions',
      'Move between fractions, decimals, percentages, and multipliers.',
      'Arithmetic is about 33-45% of QA.',
      '2023-25 trend: Arithmetic roughly 7-11 questions per slot.',
      'Memorise common fraction-percent pairs.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_percentages_change',
      'Successive percentage change',
      'Handle increase, decrease, and net percentage change.',
      'High Arithmetic frequency.',
      'Appears often in arithmetic-driven QA papers.',
      'Use multiplier method.',
    ),
    const PrepSubtopic(
      'qa_percentages_base',
      'Base value traps',
      'Know what the percentage is being taken of.',
      'Common trap in CAT arithmetic.',
      'Relevant across profit-loss, DI, and growth questions.',
      'Write "of what?" beside every percentage.',
    ),
    const PrepSubtopic(
      'qa_percentages_comparison',
      'Comparison and index',
      'Compare two values through percentage difference and index forms.',
      'High support skill.',
      'Useful in QA and DI every year.',
      'Use 100 as a smart base.',
    ),
  ],
  'qa_averages': [
    const PrepSubtopic(
      'qa_averages_simple',
      'Simple averages',
      'Use sum = average x count fluently.',
      'High Arithmetic frequency.',
      'Arithmetic remains a dominant QA bucket in 2020-25.',
      'Write total first, average second.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_averages_weighted',
      'Weighted averages',
      'Handle groups with different sizes and averages.',
      'Common CAT arithmetic type.',
      'Appears through averages, mixtures, and DI.',
      'Use alligation only after understanding weights.',
    ),
    const PrepSubtopic(
      'qa_averages_mixtures',
      'Mixtures and alligation',
      'Solve replacement, concentration, and blending problems.',
      'High-value Arithmetic subtopic.',
      'Repeated across recent prep analyses as core Arithmetic.',
      'Track quantity and concentration separately.',
    ),
    const PrepSubtopic(
      'qa_averages_missing',
      'Missing value from average',
      'Find an unknown value after adding, removing, or replacing items.',
      'Frequent beginner-level sitter.',
      'Common in Arithmetic question pools.',
      'Use change in total instead of long equations.',
    ),
  ],
  'qa_ratio': [
    const PrepSubtopic(
      'qa_ratio_basic',
      'Basic ratios',
      'Convert ratios into parts, totals, and actual values.',
      'High Arithmetic frequency.',
      'Ratio/proportion is a core recurring Arithmetic area.',
      'Let one part be x.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_ratio_proportion',
      'Direct and inverse proportion',
      'Connect two variables correctly based on how they change.',
      'Common in Arithmetic word problems.',
      'Useful in time-work, speed, and variation questions.',
      'Check direction of change before forming equation.',
    ),
    const PrepSubtopic(
      'qa_ratio_variation',
      'Variation',
      'Handle joint, direct, and inverse variation statements.',
      'Moderate QA frequency.',
      'Rotates within Arithmetic and Algebra crossover questions.',
      'Translate words into k equations.',
    ),
    const PrepSubtopic(
      'qa_ratio_partnership',
      'Partnership and sharing',
      'Divide profit, work, or value by investment and time ratios.',
      'Common Arithmetic application.',
      'Often appears as ratio-plus-profit-loss style questions.',
      'Use investment x time as effective share.',
    ),
  ],
  'qa_profit_loss': [
    const PrepSubtopic(
      'qa_profit_loss_basic',
      'Profit and loss basics',
      'Connect CP, SP, profit, loss, and percentage.',
      'High Arithmetic frequency.',
      'Profit-loss appears regularly in Arithmetic-heavy CAT QA.',
      'Use CP = 100 unless numbers suggest otherwise.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_profit_loss_discount',
      'Marked price and discount',
      'Handle MP, discount, SP, and chained discounts.',
      'Common QA application.',
      'Seen often in prep trend lists and mocks.',
      'Convert discounts into multipliers.',
    ),
    const PrepSubtopic(
      'qa_profit_loss_interest',
      'Simple and compound interest',
      'Solve SI, CI, annual growth, and effective rate problems.',
      'Core Arithmetic bucket.',
      'Recurring but not guaranteed every slot.',
      'Use CI multiplier and SI linear growth.',
    ),
    const PrepSubtopic(
      'qa_profit_loss_business',
      'Business arithmetic',
      'Work with taxes, margins, successive pricing, and break-even logic.',
      'High application value.',
      'CAT often wraps percentages in business stories.',
      'Draw a money-flow table.',
    ),
  ],
  'qa_tsd': [
    const PrepSubtopic(
      'qa_tsd_speed_time_distance',
      'Speed-time-distance basics',
      'Use distance = speed x time and unit conversion.',
      'High Arithmetic frequency.',
      'TSD is a recurring Arithmetic family.',
      'Convert km/h to m/s only when needed.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_tsd_relative_speed',
      'Relative speed',
      'Handle trains, races, meetings, and overtaking.',
      'Common CAT Arithmetic type.',
      'Appears regularly in arithmetic practice sets.',
      'Same direction subtract, opposite direction add.',
    ),
    const PrepSubtopic(
      'qa_tsd_boats_streams',
      'Boats and streams',
      'Use upstream/downstream speed relationships.',
      'Moderate frequency.',
      'Rotates within TSD; not guaranteed every slot.',
      'Let still-water speed and stream speed be separate variables.',
    ),
    const PrepSubtopic(
      'qa_tsd_circular_tracks',
      'Circular tracks',
      'Solve meetings, laps, and relative motion on a track.',
      'Moderate to advanced.',
      'Seen in current mock and past-paper style problems.',
      'Use LCM of times for repeat meetings.',
      difficulty: 'Advanced',
    ),
  ],
  'qa_time_work': [
    const PrepSubtopic(
      'qa_time_work_efficiency',
      'Efficiency basics',
      'Translate time taken into work rate.',
      'High Arithmetic family.',
      'Time-work is part of core Arithmetic trend lists.',
      'Use total work as LCM of times.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_time_work_combined',
      'Combined work',
      'Handle people working together or separately.',
      'Common QA type.',
      'Recurring in CAT-style Arithmetic.',
      'Add rates, not times.',
    ),
    const PrepSubtopic(
      'qa_time_work_pipes',
      'Pipes and cisterns',
      'Apply positive and negative work rates.',
      'Moderate frequency.',
      'Rotates within time-work applications.',
      'Filling is positive, emptying is negative.',
    ),
    const PrepSubtopic(
      'qa_time_work_wages',
      'Work and wages',
      'Distribute payment by efficiency and time worked.',
      'Useful Arithmetic application.',
      'Appears in practice pools more than every CAT slot.',
      'Pay share follows work share.',
    ),
  ],
  'qa_linear_quadratic': [
    const PrepSubtopic(
      'qa_linear_quadratic_linear',
      'Linear equations',
      'Translate word statements into one or more equations.',
      'Algebra is about 23-36% of QA.',
      '2023-25 trend: Algebra roughly 4-8 questions per slot.',
      'Define variables before writing equations.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_linear_quadratic_quadratic',
      'Quadratic equations',
      'Use roots, factorisation, discriminant, and signs.',
      'Core Algebra area.',
      'Recurring within Algebra-heavy QA papers.',
      'Check if factorisation is faster than formula.',
    ),
    const PrepSubtopic(
      'qa_linear_quadratic_word',
      'Equation word problems',
      'Convert ages, numbers, and conditions into equations.',
      'High-value Algebra-Arithmetic crossover.',
      'Appears often as setup-based QA sitters.',
      'Do not solve before all variables are defined.',
    ),
    const PrepSubtopic(
      'qa_linear_quadratic_roots',
      'Roots and coefficients',
      'Use sum/product of roots and related transformations.',
      'Moderate Algebra frequency.',
      'Rotates yearly inside Algebra.',
      'Write alpha + beta and alpha beta first.',
    ),
  ],
  'qa_inequalities': [
    const PrepSubtopic(
      'qa_inequalities_basic',
      'Linear inequalities',
      'Solve and represent solution ranges cleanly.',
      'Common Algebra support skill.',
      'Appears directly or inside functions/modulus questions.',
      'Use number line notation.',
    ),
    const PrepSubtopic(
      'qa_inequalities_quadratic',
      'Quadratic inequalities',
      'Use sign charts around critical points.',
      'Moderate to advanced Algebra.',
      'Rotates inside Algebra question sets.',
      'Factor first, then mark intervals.',
    ),
    const PrepSubtopic(
      'qa_inequalities_modulus',
      'Modulus',
      'Split cases based on sign or use distance interpretation.',
      'Advanced Algebra subtopic.',
      'Appears in some CAT-style Algebra papers and mocks.',
      'Write cases only after identifying breakpoints.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'qa_inequalities_ranges',
      'Range of expressions',
      'Find possible values under constraints.',
      'Advanced score differentiator.',
      'Rotates yearly, not guaranteed.',
      'Combine algebraic manipulation with boundary checks.',
      difficulty: 'Advanced',
    ),
  ],
  'qa_functions_logs': [
    const PrepSubtopic(
      'qa_functions_logs_function_basics',
      'Function basics',
      'Understand input, output, domain, range, and notation.',
      'Common Algebra family.',
      'Functions recur within Algebra trend lists.',
      'Substitute carefully before simplifying.',
    ),
    const PrepSubtopic(
      'qa_functions_logs_composition',
      'Composition and inverse',
      'Handle f(g(x)), inverse functions, and repeated operations.',
      'Moderate Algebra value.',
      'Appears in Algebra-heavy QA papers and mocks.',
      'Work from the inside out.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'qa_functions_logs_log_rules',
      'Logarithm rules',
      'Use product, quotient, power, and base-change rules.',
      'Common Algebra support area.',
      'Logs rotate within Algebra questions.',
      'Convert log equations to exponent form.',
    ),
    const PrepSubtopic(
      'qa_functions_logs_graphs',
      'Graphs and domains',
      'Use graph sense for functions, restrictions, and roots.',
      'Moderate to advanced.',
      'Graph-based algebra appears occasionally.',
      'Check denominator, square-root, and log domain restrictions.',
      difficulty: 'Advanced',
    ),
  ],
  'qa_algebra_polynomials': [
    const PrepSubtopic(
      'qa_algebra_polynomials_basic',
      'Polynomials',
      'Work with polynomial expressions, roots, factors, and values.',
      'Common Algebra support area.',
      'Polynomials are part of standard Algebra coverage.',
      'Check factor theorem and simple substitution before expanding.',
    ),
    const PrepSubtopic(
      'qa_algebra_polynomials_identities',
      'Algebraic identities',
      'Use standard identities for expansion, factorisation, and simplification.',
      'High support value.',
      'Identity manipulation supports equations and functions.',
      'Recognise squares, cubes, and difference of squares quickly.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_algebra_polynomials_indices',
      'Indices',
      'Simplify powers, exponents, and index equations.',
      'Common Algebra support skill.',
      'Indices appear inside equations, logs, and number-system questions.',
      'Reduce expressions to common bases when possible.',
    ),
    const PrepSubtopic(
      'qa_algebra_polynomials_surds',
      'Surds',
      'Simplify roots, rationalise denominators, and compare irrational values.',
      'Common Algebra support skill.',
      'Surds are included in broad Algebra syllabi.',
      'Convert to prime factors and simplify before calculating.',
    ),
  ],
  'qa_sequences': [
    const PrepSubtopic(
      'qa_sequences_ap',
      'Arithmetic progression',
      'Use nth term, sum, and average of terms.',
      'Common Algebra/Modern support area.',
      'Progressions appear periodically in QA.',
      'Write a, d, n before applying formulas.',
    ),
    const PrepSubtopic(
      'qa_sequences_gp',
      'Geometric progression',
      'Use common ratio, nth term, and finite sum.',
      'Moderate frequency.',
      'Rotates inside Algebra and Modern Math.',
      'Check whether ratio is less than, equal to, or greater than 1.',
    ),
    const PrepSubtopic(
      'qa_sequences_hp',
      'Harmonic progression',
      'Convert HP into AP of reciprocals.',
      'Low to moderate frequency.',
      'Mentioned in broad syllabi, less frequent than AP/GP.',
      'Use only after AP/GP is solid.',
    ),
    const PrepSubtopic(
      'qa_sequences_patterns',
      'Number patterns',
      'Identify pattern logic without overfitting.',
      'Rotating Algebra skill.',
      'Useful in sequence/pattern style questions.',
      'Test first differences and ratios.',
    ),
  ],
  'qa_geometry_triangles': [
    const PrepSubtopic(
      'qa_geometry_triangles_lines_angles',
      'Lines and angles',
      'Use parallel lines, transversals, angle chasing, and basic theorems.',
      'Core Geometry support skill.',
      'Lines and angles support most geometry questions.',
      'Mark equal, supplementary, and alternate angles on the diagram.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_geometry_triangles_triangles',
      'Triangles',
      'Cover similarity, congruence, angles, area, and special triangles.',
      'Geometry is about 10-18% of QA.',
      '2023-25 trend: Geometry roughly 3-5 questions per slot.',
      'Draw clean figures and mark equal angles.',
    ),
    const PrepSubtopic(
      'qa_geometry_triangles_circles',
      'Circles',
      'Use chords, tangents, cyclic quadrilaterals, and arcs.',
      'Core Geometry area.',
      'Recurring in geometry question pools.',
      'Look for tangent-radius perpendiculars.',
    ),
    const PrepSubtopic(
      'qa_geometry_triangles_polygons',
      'Polygons',
      'Use interior/exterior angles, diagonals, and regular polygon facts.',
      'Moderate Geometry frequency.',
      'Rotates yearly inside Geometry.',
      'Break polygons into triangles.',
    ),
    const PrepSubtopic(
      'qa_geometry_triangles_quadrilaterals',
      'Quadrilaterals',
      'Use properties of parallelograms, rectangles, squares, rhombus, trapezium, and cyclic quadrilaterals.',
      'Core Geometry area.',
      'Quadrilateral properties recur within geometry questions.',
      'Check parallel sides, diagonals, and angle sums first.',
    ),
    const PrepSubtopic(
      'qa_geometry_triangles_trig',
      'Basic trigonometry',
      'Use standard ratios and identities only as needed.',
      'Low to moderate CAT frequency.',
      'Appears occasionally with geometry or coordinate ideas.',
      'Keep standard angle values ready.',
    ),
  ],
  'qa_coordinate_mensuration': [
    const PrepSubtopic(
      'qa_coordinate_mensuration_lines',
      'Lines and slopes',
      'Use slope, intercept, distance, and midpoint.',
      'Moderate Geometry frequency.',
      'Coordinate basics rotate in QA.',
      'Draw axes and label points.',
    ),
    const PrepSubtopic(
      'qa_coordinate_mensuration_area',
      '2D mensuration',
      'Handle area and perimeter of standard figures.',
      'Common Geometry support area.',
      'Appears in geometry/mensuration trend lists.',
      'Memorise formulas, but draw before using them.',
    ),
    const PrepSubtopic(
      'qa_coordinate_mensuration_volume',
      '3D mensuration',
      'Use volume and surface area of cubes, cylinders, cones, and spheres.',
      'Moderate to low frequency.',
      'Rotates yearly; not guaranteed every slot.',
      'Track units carefully.',
    ),
    const PrepSubtopic(
      'qa_coordinate_mensuration_mixed',
      'Mixed geometry applications',
      'Combine coordinate, area, and ratio ideas.',
      'Advanced Geometry type.',
      'Useful in tougher geometry questions.',
      'Search for similar triangles or equal ratios.',
      difficulty: 'Advanced',
    ),
  ],
  'qa_number_system': [
    const PrepSubtopic(
      'qa_number_system_properties',
      'Properties of numbers',
      'Understand integers, primes, composites, parity, factors, multiples, and divisibility structure.',
      'Core Number Systems foundation.',
      'Number-property thinking supports most Number Systems questions.',
      'Prime factorise and note parity before solving.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_number_system_divisibility',
      'Divisibility',
      'Use divisibility rules and factor structure.',
      'Number Systems about 5-15% of QA.',
      'Recent trend: usually about 1-2 questions in many slots.',
      'Prime factorise early.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_number_system_remainders',
      'Remainders',
      'Use modular arithmetic, cycles, and negative remainders.',
      'Moderate Number Systems value.',
      'Remainder questions rotate yearly.',
      'Reduce numbers before exponentiating.',
    ),
    const PrepSubtopic(
      'qa_number_system_factors',
      'Factors and multiples',
      'Find number of factors, odd/even factors, HCF, and LCM.',
      'Core Number Systems area.',
      'Appears periodically in CAT QA.',
      'Use prime powers.',
    ),
    const PrepSubtopic(
      'qa_number_system_hcf_lcm',
      'HCF and LCM',
      'Use prime factors, common factors, common multiples, and LCM-based counting.',
      'Core Number Systems area.',
      'HCF-LCM ideas appear directly and inside word problems.',
      'Break each number into prime powers before combining.',
    ),
    const PrepSubtopic(
      'qa_number_system_integers',
      'Integer constraints',
      'Solve positive integer and divisibility condition questions.',
      'Moderate to advanced.',
      'Rotates inside number theory and algebra.',
      'List possible values only after bounding them.',
      difficulty: 'Advanced',
    ),
  ],
  'qa_digits_bases': [
    const PrepSubtopic(
      'qa_digits_bases_units',
      'Units digit',
      'Use cyclicity for powers and products.',
      'Low to moderate frequency.',
      'Often appears as one possible Number Systems question.',
      'Memorise cycles 2-9.',
      difficulty: 'Beginner',
    ),
    const PrepSubtopic(
      'qa_digits_bases_digits',
      'Digit problems',
      'Handle two-digit, three-digit, reversal, and sum-of-digits conditions.',
      'Moderate frequency.',
      'Rotates inside Number Systems.',
      'Represent a two-digit number as 10a + b.',
    ),
    const PrepSubtopic(
      'qa_digits_bases_base_system',
      'Base systems',
      'Convert between bases and decimal values.',
      'Low frequency but included in syllabus lists.',
      'Appears rarely; prepare after core topics.',
      'Use place values from right to left.',
    ),
    const PrepSubtopic(
      'qa_digits_bases_surds',
      'Indices and surds',
      'Simplify exponents, roots, and rationalisation.',
      'Support skill for Algebra and Number Systems.',
      'Useful across algebraic simplification questions.',
      'Reduce to prime powers where possible.',
    ),
  ],
  'qa_sets_pnc_probability': [
    const PrepSubtopic(
      'qa_sets_pnc_probability_sets',
      'Set theory',
      'Use Venn diagrams, inclusion-exclusion, and overlaps.',
      'Modern Math about 0-14% of QA.',
      'Recent trend: Modern Math can range from 0 to about 4 questions.',
      'Draw Venn regions before equations.',
    ),
    const PrepSubtopic(
      'qa_sets_pnc_probability_venn',
      'Venn diagrams',
      'Represent two-set and three-set overlaps using clean regions.',
      'Modern Math and DILR support skill.',
      'Venn diagrams are included in broad Modern Math coverage.',
      'Fill exact-only regions before totals.',
    ),
    const PrepSubtopic(
      'qa_sets_pnc_probability_pnc',
      'Permutations and combinations',
      'Count arrangements and selections under restrictions.',
      'Rotating Modern Math area.',
      'Not guaranteed every slot, but high value when present.',
      'Decide selection or arrangement first.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'qa_sets_pnc_probability_probability',
      'Probability',
      'Use favourable outcomes over total outcomes.',
      'Rotating Modern Math area.',
      'Appears occasionally with P&C and set logic.',
      'Count carefully before applying formula.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'qa_sets_pnc_probability_binomial',
      'Binomial basics',
      'Know expansion ideas and coefficient logic.',
      'Low frequency.',
      'Mentioned in broad syllabi, less frequent than Arithmetic/Algebra.',
      'Keep it for coverage after high-priority topics.',
    ),
  ],
  'qa_maxima_integer': [
    const PrepSubtopic(
      'qa_maxima_integer_max_min',
      'Maxima and minima',
      'Find best possible value under algebraic constraints.',
      'Advanced rotating Algebra.',
      'Appears occasionally; not a first-pass topic.',
      'Check boundary values and equality cases.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'qa_maxima_integer_integer_solutions',
      'Integer solutions',
      'Count solutions to equations or inequalities under integer constraints.',
      'Rotating Algebra/Number crossover.',
      'Useful when CAT shifts to casework questions.',
      'Bound variables before counting.',
      difficulty: 'Advanced',
    ),
    const PrepSubtopic(
      'qa_maxima_integer_ages',
      'Ages and integer word problems',
      'Turn age relationships into clean equations.',
      'Low to moderate frequency.',
      'May appear as Algebra-Arithmetic crossover.',
      'Use current age variables and timeline columns.',
    ),
    const PrepSubtopic(
      'qa_maxima_integer_casework',
      'Casework discipline',
      'Know when to split cases and when to skip.',
      'Advanced score management.',
      'Important for hard QA questions in mocks.',
      'If cases keep expanding, mark and return later.',
      difficulty: 'Advanced',
    ),
  ],
};

const List<DailyTask> dailyTasks = [
  DailyTask(
    id: 'daily_rc',
    section: CatSection.varc,
    title: 'Read and analyse one RC passage',
    detail: 'Main idea, tone, structure, and one trap option.',
    minutes: 35,
  ),
  DailyTask(
    id: 'daily_qa',
    section: CatSection.qa,
    title: 'QA concept plus timed drill',
    detail: 'Arithmetic or Algebra concept, then 15 timed questions.',
    minutes: 60,
  ),
  DailyTask(
    id: 'daily_dilr',
    section: CatSection.dilr,
    title: 'Solve one DILR set',
    detail: 'Write the table/grid setup and a skip-or-solve note.',
    minutes: 40,
  ),
  DailyTask(
    id: 'daily_review',
    section: null,
    title: 'Update error log',
    detail: 'Record formula gaps, concept misses, and selection lessons.',
    minutes: 20,
  ),
];

final List<MockSlot> mockSlots = [
  MockSlot(
    id: 'mock_diagnostic',
    title: 'Diagnostic mock',
    date: DateTime(2026, 6, 16),
    focus: 'Baseline only; score is less important than diagnosis.',
    kind: 'Diagnostic',
  ),
  MockSlot(
    id: 'mock_sectional_jun_28',
    title: 'Two sectionals',
    date: DateTime(2026, 6, 28),
    focus: 'One VARC sectional and one DILR or QA sectional.',
    kind: 'Sectional',
  ),
  MockSlot(
    id: 'mock_cat_2020_s1',
    title: 'CAT 2020 Slot 1 simulation',
    date: DateTime(2026, 7, 12),
    focus: 'First previous-year full paper with full review.',
    kind: 'PYQ',
  ),
  MockSlot(
    id: 'mock_cat_2021_s2',
    title: 'CAT 2021 Slot 2 simulation',
    date: DateTime(2026, 7, 26),
    focus: 'Check selection discipline and QA first-pass accuracy.',
    kind: 'PYQ',
  ),
  MockSlot(
    id: 'mock_cat_2022_s1',
    title: 'CAT 2022 Slot 1 simulation',
    date: DateTime(2026, 8, 9),
    focus: 'Begin organised current-format paper rotation.',
    kind: 'PYQ',
  ),
  MockSlot(
    id: 'mock_cat_2023_s1',
    title: 'CAT 2023 Slot 1 simulation',
    date: DateTime(2026, 8, 23),
    focus: 'One full paper plus two days of error-log patching.',
    kind: 'PYQ',
  ),
  MockSlot(
    id: 'mock_cat_2024_s1',
    title: 'CAT 2024 Slot 1 simulation',
    date: DateTime(2026, 9, 6),
    focus: 'Five-set DILR rhythm and modern VARC balance.',
    kind: 'PYQ',
  ),
  MockSlot(
    id: 'mock_cat_2025_s1',
    title: 'CAT 2025 Slot 1 simulation',
    date: DateTime(2026, 9, 20),
    focus: 'Latest completed pattern: 24/22/22 base case.',
    kind: 'PYQ',
  ),
  MockSlot(
    id: 'mock_oct_04',
    title: 'October mock 1',
    date: DateTime(2026, 10, 4),
    focus: 'Attempt strategy, skipped questions, and concept misses.',
    kind: 'Full mock',
  ),
  MockSlot(
    id: 'mock_oct_11',
    title: 'October mock 2',
    date: DateTime(2026, 10, 11),
    focus: 'Deep review before adding more tests.',
    kind: 'Full mock',
  ),
  MockSlot(
    id: 'mock_oct_18',
    title: 'October mock 3',
    date: DateTime(2026, 10, 18),
    focus: 'Percentile-building month: speed plus accuracy.',
    kind: 'Full mock',
  ),
  MockSlot(
    id: 'mock_oct_25',
    title: 'October mock 4',
    date: DateTime(2026, 10, 25),
    focus: 'Sectional balance and time allocation.',
    kind: 'Full mock',
  ),
  MockSlot(
    id: 'mock_nov_01',
    title: 'November mock 1',
    date: DateTime(2026, 11, 1),
    focus: 'Revision-led mock with settled attempt order.',
    kind: 'Full mock',
  ),
  MockSlot(
    id: 'mock_nov_08',
    title: 'November mock 2',
    date: DateTime(2026, 11, 8),
    focus: 'Final stretch: selection, stamina, and RC consistency.',
    kind: 'Full mock',
  ),
  MockSlot(
    id: 'mock_nov_15',
    title: 'Official interface mock',
    date: DateTime(2026, 11, 15),
    focus: 'Use the official mock interface when CAT 2026 link appears.',
    kind: 'Interface',
  ),
  MockSlot(
    id: 'mock_nov_22',
    title: 'Final light mock',
    date: DateTime(2026, 11, 22),
    focus: 'Final full-length calibration, then mostly revision.',
    kind: 'Full mock',
  ),
];

const List<PreviousYearPaper> previousYearPapers = [
  PreviousYearPaper(
    id: 'pyq_2017_s1',
    year: 2017,
    slot: 'Slot 1',
    questions: '100 Q old-pattern practice',
    note: 'Use for topic familiarity, not timing benchmark.',
  ),
  PreviousYearPaper(
    id: 'pyq_2017_s2',
    year: 2017,
    slot: 'Slot 2',
    questions: '100 Q old-pattern practice',
    note: 'Good for extra QA/VARC/DILR exposure.',
  ),
  PreviousYearPaper(
    id: 'pyq_2018_s1',
    year: 2018,
    slot: 'Slot 1',
    questions: '100 Q old-pattern practice',
    note: 'Use after foundations for breadth.',
  ),
  PreviousYearPaper(
    id: 'pyq_2018_s2',
    year: 2018,
    slot: 'Slot 2',
    questions: '100 Q old-pattern practice',
    note: 'Treat timing lightly because pattern differs.',
  ),
  PreviousYearPaper(
    id: 'pyq_2019_s1',
    year: 2019,
    slot: 'Slot 1',
    questions: '100 Q old-pattern practice',
    note: 'Useful for strong QA and VARC practice.',
  ),
  PreviousYearPaper(
    id: 'pyq_2019_s2',
    year: 2019,
    slot: 'Slot 2',
    questions: '100 Q old-pattern practice',
    note: 'Last pre-120-minute full paper year.',
  ),
  PreviousYearPaper(
    id: 'pyq_2020_s1',
    year: 2020,
    slot: 'Slot 1',
    questions: '76 Q current-era paper',
    note: 'First 120-minute era; strong simulation value.',
  ),
  PreviousYearPaper(
    id: 'pyq_2020_s2',
    year: 2020,
    slot: 'Slot 2',
    questions: '76 Q current-era paper',
    note: 'Use as full paper after diagnostic phase.',
  ),
  PreviousYearPaper(
    id: 'pyq_2020_s3',
    year: 2020,
    slot: 'Slot 3',
    questions: '76 Q current-era paper',
    note: 'Good for extra current-era practice.',
  ),
  PreviousYearPaper(
    id: 'pyq_2021_s1',
    year: 2021,
    slot: 'Slot 1',
    questions: '66 Q current-era paper',
    note: 'Very relevant 24/20/22 rhythm.',
  ),
  PreviousYearPaper(
    id: 'pyq_2021_s2',
    year: 2021,
    slot: 'Slot 2',
    questions: '66 Q current-era paper',
    note: 'Scheduled in your starter mock plan.',
  ),
  PreviousYearPaper(
    id: 'pyq_2021_s3',
    year: 2021,
    slot: 'Slot 3',
    questions: '66 Q current-era paper',
    note: 'Use for rotation after core basics.',
  ),
  PreviousYearPaper(
    id: 'pyq_2022_s1',
    year: 2022,
    slot: 'Slot 1',
    questions: '66 Q current-era paper',
    note: 'Scheduled in your integration phase.',
  ),
  PreviousYearPaper(
    id: 'pyq_2022_s2',
    year: 2022,
    slot: 'Slot 2',
    questions: '66 Q current-era paper',
    note: 'Useful for sectional balance practice.',
  ),
  PreviousYearPaper(
    id: 'pyq_2022_s3',
    year: 2022,
    slot: 'Slot 3',
    questions: '66 Q current-era paper',
    note: 'Analyse skipped sets carefully.',
  ),
  PreviousYearPaper(
    id: 'pyq_2023_s1',
    year: 2023,
    slot: 'Slot 1',
    questions: '66 Q current-era paper',
    note: 'Scheduled in your integration phase.',
  ),
  PreviousYearPaper(
    id: 'pyq_2023_s2',
    year: 2023,
    slot: 'Slot 2',
    questions: '66 Q current-era paper',
    note: 'Great for QA/VARC current-pattern work.',
  ),
  PreviousYearPaper(
    id: 'pyq_2023_s3',
    year: 2023,
    slot: 'Slot 3',
    questions: '66 Q current-era paper',
    note: 'Use before entering weekly mock phase.',
  ),
  PreviousYearPaper(
    id: 'pyq_2024_s1',
    year: 2024,
    slot: 'Slot 1',
    questions: '68 Q latest-pattern paper',
    note: 'Five-set DILR rhythm; very important.',
  ),
  PreviousYearPaper(
    id: 'pyq_2024_s2',
    year: 2024,
    slot: 'Slot 2',
    questions: '68 Q latest-pattern paper',
    note: 'Use for late rotation and set-selection practice.',
  ),
  PreviousYearPaper(
    id: 'pyq_2024_s3',
    year: 2024,
    slot: 'Slot 3',
    questions: '68 Q latest-pattern paper',
    note: 'High relevance to CAT 2026 assumption.',
  ),
  PreviousYearPaper(
    id: 'pyq_2025_s1',
    year: 2025,
    slot: 'Slot 1',
    questions: '68 Q latest-pattern paper',
    note: 'Latest completed pattern; priority paper.',
  ),
  PreviousYearPaper(
    id: 'pyq_2025_s2',
    year: 2025,
    slot: 'Slot 2',
    questions: '68 Q latest-pattern paper',
    note: 'Use near peak phase after analysis habits are strong.',
  ),
  PreviousYearPaper(
    id: 'pyq_2025_s3',
    year: 2025,
    slot: 'Slot 3',
    questions: '68 Q latest-pattern paper',
    note: 'Keep for final high-relevance full-paper practice.',
  ),
];

final List<PlanPhase> planPhases = [
  PlanPhase(
    title: 'Foundation',
    range: 'June and July',
    focus: 'Build base in RC, Arithmetic, Algebra, and DILR representation.',
    actions: [
      'Take one diagnostic mock immediately.',
      'Read daily and analyse RC options.',
      'Finish Arithmetic basics and begin Algebra.',
      'Solve 3-4 DILR sets per week from week one.',
    ],
    start: DateTime(2026, 6, 13),
    end: DateTime(2026, 7, 31),
  ),
  PlanPhase(
    title: 'Core Rotation',
    range: 'August and September',
    focus: 'Finish core syllabus and rotate through sectionals plus PYQs.',
    actions: [
      'Complete major QA buckets and all common VA formats.',
      'See enough DILR archetypes that nothing feels alien.',
      'Take one sectional every 3-4 days.',
      'Start organised 2021-2025 paper rotation.',
    ],
    start: DateTime(2026, 8),
    end: DateTime(2026, 9, 30),
  ),
  PlanPhase(
    title: 'Percentile Build',
    range: 'October',
    focus: 'Move from syllabus coverage to mock-led improvement.',
    actions: [
      'Take one full mock per week, two if work allows.',
      'Analyse harder than you write the mock.',
      'Track what to skip, what to solve faster, and concept misses.',
      'Patch weak topic clusters using the error log.',
    ],
    start: DateTime(2026, 10),
    end: DateTime(2026, 10, 31),
  ),
  PlanPhase(
    title: 'Revision and Exam Calm',
    range: 'November to exam day',
    focus: 'Keep strategy settled and avoid heavy new theory.',
    actions: [
      'Lean on mocks, PYQs, revision sheets, and official interface practice.',
      'Drill DILR set selection and RC consistency.',
      'Review formula cards and repeated mistakes.',
      'Arrive with a settled section strategy.',
    ],
    start: DateTime(2026, 11),
    end: DateTime(2026, 11, 29),
  ),
];

const List<ResourceItem> resourceStack = [
  ResourceItem(
    title: 'Official CAT website and official mock',
    useFor: 'Truth source',
    note:
        'Use for bulletin, registration, admit card, response sheet, and interface familiarity.',
  ),
  ResourceItem(
    title: '2IIM, Career Launcher, and Cracku PYQs',
    useFor: 'Previous papers',
    note:
        'Use 2021-2025 heavily because they match the current 120-minute era best.',
  ),
  ResourceItem(
    title: 'Rodha, IMS, 2IIM, Cracku, MBA Pathshala',
    useFor: 'Free concept and strategy stack',
    note:
        'Pick one main teacher per topic, then let past papers be the common language.',
  ),
  ResourceItem(
    title: 'Error log and revision cards',
    useFor: 'Score compounding',
    note: 'Do not take two full tests without finishing analysis of the first.',
  ),
];

const List<String> motivationLines = [
  'Small honest reps beat panic every time.',
  'Today is not for proving. Today is for building.',
  'One clean set, one clean passage, one clean concept.',
  'Accuracy first. Speed follows clean thinking.',
  'The mock reveals the ceiling. The analysis raises it.',
  'Skip with discipline. Solve with calm.',
  'You are not behind if you are consistent today.',
];
